version: '3.9'

services:
  db:
    image: postgres:13
    container_name: test_cat_db
    environment:
      POSTGRES_DB: cats_db
      POSTGRES_USER: cats_ceo
      POSTGRES_PASSWORD: sca_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: test_cat_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=cats_db
      - DATABASE_USER=cats_ceo
      - DATABASE_PASSWORD=sca_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: